//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Customer_Languages = new HashSet<Customer_Languages>();
        }
    
        public System.Guid CustomerId_PK { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> CountryID_FK { get; set; }
        public Nullable<System.Guid> StateID_FK { get; set; }
        public Nullable<System.Guid> CityID_FK { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Customer_Languages> Customer_Languages { get; set; }
        public virtual State State { get; set; }
    }
}
