//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Languages
    {
        public System.Guid Id_PK { get; set; }
        public Nullable<System.Guid> LanguageID_FK { get; set; }
        public Nullable<System.Guid> CustomerID_FK { get; set; }
        public Nullable<bool> isPrimary { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Language Language { get; set; }
    }
}
