//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.Customer_Languages = new HashSet<Customer_Languages>();
        }
    
        public System.Guid LanguageId_PK { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Customer_Languages> Customer_Languages { get; set; }
    }
}
