//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicControl.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ReportDatabaseEntities : DbContext
    {
        public ReportDatabaseEntities()
            : base("name=ReportDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_Languages> Customer_Languages { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<WebReportCatalogue> WebReportCatalogues { get; set; }
        public virtual DbSet<WebReportParameter> WebReportParameters { get; set; }
        public virtual DbSet<WebReportServer> WebReportServers { get; set; }
        public virtual DbSet<WebReportParamCascadeMapping> WebReportParamCascadeMappings { get; set; }
    
        public virtual ObjectResult<Get_CustomerLanguages_Result> Get_CustomerLanguages()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_CustomerLanguages_Result>("Get_CustomerLanguages");
        }
    
        public virtual ObjectResult<Get_CustomerLanguages_Result> Get_CustomerReportLanguages(string cParams)
        {
            var cParamsParameter = cParams != null ?
                new ObjectParameter("cParams", cParams) :
                new ObjectParameter("cParams", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_CustomerLanguages_Result>("Get_CustomerReportLanguages", cParamsParameter);
        }
    }
}
