//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebReportParameter
    {
        public System.Guid RPId_PK { get; set; }
        public string Name { get; set; }
        public string ControlType { get; set; }
        public string ColumnName { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.Guid> ReportId_FK { get; set; }
        public Nullable<int> OrderByControl { get; set; }
        public string ngModel { get; set; }
    
        public virtual WebReportCatalogue WebReportCatalogue { get; set; }
    }
}
