//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebReportParamCascadeMapping
    {
        public System.Guid ReportId_FK { get; set; }
        public System.Guid PRId_FK { get; set; }
        public Nullable<System.Guid> CascadeRPId_FK { get; set; }
        public Nullable<int> OrderByControl { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
